### ISSUE TITLE
Space before function

### ISSUE THREAD

**Issue by jernejrostan** [baixuexiyang/VUEFormatter#2]
Most linters want a space before function. Is it possible to add this ?

**Comment by jericopulvera** [comment]
It is possible.

**Comment by jernejrostan** [comment]
how? :)

**Comment by rashnk** [comment]
how ?

"space_after_anon_function": true, // Should the space before an anonymous function's parens be added, "function()" vs "function ()"
      "space_before_conditional": true, // Should the space before conditional statement be added, "if(true)" vs "if (true)"

its not working , space is not added

**Comment by rashnk** [comment]
```
props: ['chapter', 'option'],
  data() {
    return {
      pscroll: {
        width: '0',
        height: (height - 128) + 'px'
      }
    }
  },
```
in this example, data () space is not added
